#!/bin/sh -e
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

case ${1} in
	remove|upgrade|deconfigure)
		
		for ALT in $(ls -1 /usr/share/themes/Gnamon/gnome-shell/); do
			
			update-alternatives --remove \
			${ALT} \
			/usr/share/themes/Gnamon/gnome-shell/${ALT}
		
		done
		
	;;
esac

#DEBHELPER#

exit 0
